# ----------------------------------------------------------------------
# |
# |  event_on_push.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 10:07:27
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main

concurrency: "on_push-${{ github.ref_name }}"

jobs:
  _545be203-55eb-4d41-bd97-43da41be2841:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_Backup/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}

  _768182e2-18ef-4a0b-9c45-1a0bf54d49a1:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-v1

    needs:
      - _545be203-55eb-4d41-bd97-43da41be2841
