# ----------------------------------------------------------------------
# |
# |  event_on_pr.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 10:06:47
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on pull request"
run-name: "${{ github.run_number }} [${{ github.actor }}] ${{ github.head_ref }} -> ${{ github.base_ref }}"

on:
  pull_request:
    branches:
      - main

jobs:
  _ee5e9719-d690-4256-adae-dd822c670556:
    name: "Validate (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-DavidBrownell_Backup/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: ${{ github.head_ref }}

  _868e1570-c24c-42a0-b6b1-b44b2e3a37fc:
    name: "Validate Pull Request (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate_pull_request.yaml@CI-v1
    with:
      job_name_prefix: DavidBrownell_Backup
      repo_name: davidbrownell/v4-DavidBrownell_Backup
      repo_branch: ${{ github.head_ref }}
      os: ubuntu-latest
      configuration: dev
