# ----------------------------------------------------------------------
# |
# |  manual_validate_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 10:15:16
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate (including dependencies)"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _4e260946-85a5-4e3e-8aa6-f3c16b1d92d3:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-DavidBrownell_Backup/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}
