# ----------------------------------------------------------------------
# |
# |  manual_validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 10:16:39
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _36ae5b87-cc37-467b-8aab-bfff6178f8bb:
    name: "Validate"
    uses: davidbrownell/v4-DavidBrownell_Backup/.github/workflows/validate.yaml@CI-BugBug # CI-latest
    with:
      repo_branch:                          ${{ github.ref_name }}
