# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/validate.jinja2.yaml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 10:10:35
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "[callable] Validates DavidBrownell_Backup"

on:
  workflow_call:
    inputs:
      repo_branch:                          {type: string, required: true}
      bootstrap_branch_overrides:           {type: string, required: false}

jobs:
  _5c74ce83-3ed7-4a5f-884f-77b19d8cd9e3:
    name: "Build and Test: standard"

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate.yaml@CI-latest
    with:
      job_name_prefix:                      "DavidBrownell_Backup"
      repo_name:                            davidbrownell/v4-DavidBrownell_Backup
      repo_branch:                          ${{ inputs.repo_branch }}
      bootstrap_branch_overrides:           ${{ inputs.bootstrap_branch_overrides }}

      os:                                   ${{ matrix.os }}
      configuration:                        standard

      run_Builder:                          true
      run_MatchTests:                       true

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests:                    3
      execute_FunctionalTests:              1
      execute_IntegrationTests:             1
      execute_SystemTests:                  1
      execute_LocalEndToEndTests:           1
      execute_EndToEndTests:                0
      execute_BuildVerificationTests:       1
      execute_PerformanceTests:             0

# Note that we aren't using a matrix for the os here as we want to increase overall throughput
# (rather than forcing the binary validation job to wait until all of the dev jobs are complete).
  # ----------------------------------------------------------------------
  # |
  # |  macos-latest
  # |
  # ----------------------------------------------------------------------
  _c22eba13-e30b-4a37-aecf-d4281fc2820b:
    name: "Build and Test: dev"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-latest
    with:
      job_name_prefix:                      "DavidBrownell_Backup"
      repo_name:                            davidbrownell/v4-DavidBrownell_Backup
      repo_branch:                          ${{ inputs.repo_branch }}
      bootstrap_branch_overrides:           ${{ inputs.bootstrap_branch_overrides }}

      os:                                   macos-latest
      configuration:                        dev

      run_PylintVerifier:                   true
      run_Builder:                          true
      run_MatchTests:                       true

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests:                    3
      execute_FunctionalTests:              1
      execute_IntegrationTests:             1
      execute_SystemTests:                  1
      execute_LocalEndToEndTests:           1
      execute_EndToEndTests:                0
      execute_BuildVerificationTests:       1
      execute_PerformanceTests:             0

  _1201e506-6400-4670-ad5f-b6c277f765fc:
    name: "DavidBrownell_Backup (macos-latest, dev binaries)"
    runs-on:                                macos-latest
    needs:
      - _c22eba13-e30b-4a37-aecf-d4281fc2820b

    steps:
      - name: "[Impl] Dump Contexts"
        if: ${{ startsWith('macos-latest', 'ubuntu') }}
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1

      # outputs:
      #   - local_script_prefix
      #   - script_extension
      #   - shell_name
      #   - source_command
      #   - sudo_command
      #   - working_dir
      #
      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1
        with:
          os:                               macos-latest

      # outputs:
      #   - archive_prefix
      #   - repo_name
      #   - repo_dir
      #
      - name: Checkout Source
        id: checkout_source
        uses: davidbrownell/v4-Common_Foundation/.github/actions/checkout_source@CI-v1
        with:
          repo_name:                        davidbrownell/v4-DavidBrownell_Backup
          repo_branch:                      ${{ inputs.repo_branch }}

          os:                               macos-latest
          configuration:                    dev

          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Unbundle Build Artifacts
        id: unbundle
        uses: davidbrownell/v4-Common_Foundation/.github/actions/unbundle_builder_artifacts@CI-latest
        with:
          archive_prefix:                   ${{ steps.checkout_source.outputs.archive_prefix }}
          artifacts_path:                   Scripts/Backup/Build

          os:                               macos-latest

          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Run Test
        run: |
          python3 "${{ steps.checkout_source.outputs.repo_dir }}/Scripts/Backup/BinaryTests/Binary_BuildVerificationTest.py" "${{ steps.unbundle.outputs.artifacts_dir }}"

  # ----------------------------------------------------------------------
  # |
  # |  ubuntu-latest
  # |
  # ----------------------------------------------------------------------
  _9b368d12-ea0c-44fd-a8d9-c8c0b464fb2c:
    name: "Build and Test: dev"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-latest
    with:
      job_name_prefix:                      "DavidBrownell_Backup"
      repo_name:                            davidbrownell/v4-DavidBrownell_Backup
      repo_branch:                          ${{ inputs.repo_branch }}
      bootstrap_branch_overrides:           ${{ inputs.bootstrap_branch_overrides }}

      os:                                   ubuntu-latest
      configuration:                        dev

      run_PylintVerifier:                   true
      run_Builder:                          true
      run_MatchTests:                       true

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests:                    3
      execute_FunctionalTests:              1
      execute_IntegrationTests:             1
      execute_SystemTests:                  1
      execute_LocalEndToEndTests:           1
      execute_EndToEndTests:                0
      execute_BuildVerificationTests:       1
      execute_PerformanceTests:             0

  _a3912995-e82d-422b-8485-370677acac36:
    name: "DavidBrownell_Backup (ubuntu-latest, dev binaries)"
    runs-on:                                ubuntu-latest
    needs:
      - _9b368d12-ea0c-44fd-a8d9-c8c0b464fb2c

    steps:
      - name: "[Impl] Dump Contexts"
        if: ${{ startsWith('ubuntu-latest', 'ubuntu') }}
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1

      # outputs:
      #   - local_script_prefix
      #   - script_extension
      #   - shell_name
      #   - source_command
      #   - sudo_command
      #   - working_dir
      #
      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1
        with:
          os:                               ubuntu-latest

      # outputs:
      #   - archive_prefix
      #   - repo_name
      #   - repo_dir
      #
      - name: Checkout Source
        id: checkout_source
        uses: davidbrownell/v4-Common_Foundation/.github/actions/checkout_source@CI-v1
        with:
          repo_name:                        davidbrownell/v4-DavidBrownell_Backup
          repo_branch:                      ${{ inputs.repo_branch }}

          os:                               ubuntu-latest
          configuration:                    dev

          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Unbundle Build Artifacts
        id: unbundle
        uses: davidbrownell/v4-Common_Foundation/.github/actions/unbundle_builder_artifacts@CI-latest
        with:
          archive_prefix:                   ${{ steps.checkout_source.outputs.archive_prefix }}
          artifacts_path:                   Scripts/Backup/Build

          os:                               ubuntu-latest

          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Run Test
        run: |
          python3 "${{ steps.checkout_source.outputs.repo_dir }}/Scripts/Backup/BinaryTests/Binary_BuildVerificationTest.py" "${{ steps.unbundle.outputs.artifacts_dir }}"

  # ----------------------------------------------------------------------
  # |
  # |  windows-latest
  # |
  # ----------------------------------------------------------------------
  _f07cf06b-98a6-433d-a807-580e35e0f031:
    name: "Build and Test: dev"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate.yaml@CI-latest
    with:
      job_name_prefix:                      "DavidBrownell_Backup"
      repo_name:                            davidbrownell/v4-DavidBrownell_Backup
      repo_branch:                          ${{ inputs.repo_branch }}
      bootstrap_branch_overrides:           ${{ inputs.bootstrap_branch_overrides }}

      os:                                   windows-latest
      configuration:                        dev

      run_PylintVerifier:                   true
      run_Builder:                          true
      run_MatchTests:                       true

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests:                    3
      execute_FunctionalTests:              1
      execute_IntegrationTests:             1
      execute_SystemTests:                  1
      execute_LocalEndToEndTests:           1
      execute_EndToEndTests:                0
      execute_BuildVerificationTests:       1
      execute_PerformanceTests:             0

  _6078471a-97d4-40fa-88cc-0cad677caa1e:
    name: "DavidBrownell_Backup (windows-latest, dev binaries)"
    runs-on:                                windows-latest
    needs:
      - _f07cf06b-98a6-433d-a807-580e35e0f031

    steps:
      - name: "[Impl] Dump Contexts"
        if: ${{ startsWith('windows-latest', 'ubuntu') }}
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1

      # outputs:
      #   - local_script_prefix
      #   - script_extension
      #   - shell_name
      #   - source_command
      #   - sudo_command
      #   - working_dir
      #
      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1
        with:
          os:                               windows-latest

      # outputs:
      #   - archive_prefix
      #   - repo_name
      #   - repo_dir
      #
      - name: Checkout Source
        id: checkout_source
        uses: davidbrownell/v4-Common_Foundation/.github/actions/checkout_source@CI-v1
        with:
          repo_name:                        davidbrownell/v4-DavidBrownell_Backup
          repo_branch:                      ${{ inputs.repo_branch }}

          os:                               windows-latest
          configuration:                    dev

          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Unbundle Build Artifacts
        id: unbundle
        uses: davidbrownell/v4-Common_Foundation/.github/actions/unbundle_builder_artifacts@CI-latest
        with:
          archive_prefix:                   ${{ steps.checkout_source.outputs.archive_prefix }}
          artifacts_path:                   Scripts/Backup/Build

          os:                               windows-latest

          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Run Test
        run: |
          python3 "${{ steps.checkout_source.outputs.repo_dir }}/Scripts/Backup/BinaryTests/Binary_BuildVerificationTest.py" "${{ steps.unbundle.outputs.artifacts_dir }}"

